---
name: Make

on:
  schedule:
    - cron:  '0 0 1 * *'
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build
      shell: bash
      run: |
        sudo bash -c 'apt-get update; apt-get install -y lazarus' >/dev/null
        read -r < <(sudo find /usr/lib/lazarus -name lazutils | sort)
        instantfpc "-Fu${REPLY}" .github/workflows/make.pas
